name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.1.3
  - pytest=8.2.2
  - scipy=1.15.2
  - pip=24.3.1
  - pip:
      - mlflow==2.20.3
      - wandb==0.18.0
